import { api } from "./client";
import type {
  Achievement,
  AchievementVisibility,
  AdminNotification,
  AdminUser,
  AnalyticsDictionary,
  Category,
  ConditionType,
  Dictionary,
  ExerciseSettings,
  Phrase,
  PhraseCategory,
  Quest,
  Rank,
  RatingSettings,
  Season,
  Slogan,
  TranslationLanguage,
  UserPhraseAnalytics,
  UserWordProgress,
  Word,
  WordDiagnostics,
  WordForm,
  WordLevel,
  WordTranslation,
} from "../types";

export async function adminLogin(login: string, password: string): Promise<string> {
  const { data } = await api.post("/auth/admin/login", { login, password });
  return data.access_token as string;
}

export async function fetchMe(): Promise<{ id: number; login: string; role: string }> {
  const { data } = await api.get("/auth/me");
  return data;
}

export async function listUsers(): Promise<AdminUser[]> {
  const { data } = await api.get("/users");
  return data;
}

export interface CreateUserInput {
  login: string;
  password: string;
  firstName: string;
  lastName: string;
  email: string;
}

// Name, surname and email are required of every new account; the 9-digit
// account number is generated by the backend and never supplied here.
export async function createUser(input: CreateUserInput): Promise<AdminUser> {
  const { data } = await api.post("/users", {
    login: input.login,
    password: input.password,
    first_name: input.firstName,
    last_name: input.lastName,
    email: input.email,
  });
  return data;
}

export async function listDictionaries(): Promise<Dictionary[]> {
  const { data } = await api.get("/dictionaries");
  return data;
}

export async function createDictionary(language: string, alphabet?: string): Promise<Dictionary> {
  const { data } = await api.post("/dictionaries", { language, alphabet: alphabet || undefined });
  return data;
}

export async function getDictionary(id: number): Promise<Dictionary> {
  const { data } = await api.get(`/dictionaries/${id}`);
  return data;
}

export async function setDictionaryPublished(id: number, isPublished: boolean): Promise<Dictionary> {
  const { data } = await api.patch(`/dictionaries/${id}`, { is_published: isPublished });
  return data;
}

export async function setDictionaryAlphabet(id: number, alphabet: string): Promise<Dictionary> {
  const { data } = await api.patch(`/dictionaries/${id}`, { alphabet });
  return data;
}

export async function deleteDictionary(id: number): Promise<void> {
  await api.delete(`/dictionaries/${id}`);
}

export async function listWords(dictionaryId: number, categoryId?: number): Promise<Word[]> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/words`, {
    params: categoryId !== undefined ? { category_id: categoryId } : undefined,
  });
  return data;
}

export async function listCategories(dictionaryId: number): Promise<Category[]> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/categories`);
  return data;
}

export async function createCategory(dictionaryId: number, name: string): Promise<Category> {
  const { data } = await api.post(`/dictionaries/${dictionaryId}/categories`, { name });
  return data;
}

/** Replaces this category's picture. Multipart, same shape as the rank and
 * achievement icon uploads -- the backend stores it under categories/{id}
 * and deletes whatever was there before. */
export async function setCategoryIcon(
  dictionaryId: number,
  categoryId: number,
  icon: File,
): Promise<Category> {
  const form = new FormData();
  form.append("icon", icon);
  const { data } = await api.put(
    `/dictionaries/${dictionaryId}/categories/${categoryId}/icon`,
    form,
  );
  return data;
}

/** Removes this category's picture; the app falls back to its own generic
 * folder icon the moment icon_url comes back null. */
export async function deleteCategoryIcon(
  dictionaryId: number,
  categoryId: number,
): Promise<Category> {
  const { data } = await api.delete(
    `/dictionaries/${dictionaryId}/categories/${categoryId}/icon`,
  );
  return data;
}

export interface CreateWordInput {
  word: string;
  translation: string;
  transcription?: string;
  categoryId?: number | null;
  wordAudio?: File | null;
  translationAudio?: File | null;
  image?: File | null;
}

export async function createWord(dictionaryId: number, input: CreateWordInput): Promise<Word> {
  const form = new FormData();
  form.append("word", input.word);
  form.append("translation", input.translation);
  if (input.transcription) form.append("transcription", input.transcription);
  if (input.categoryId != null) form.append("category_id", String(input.categoryId));
  if (input.wordAudio) form.append("word_audio", input.wordAudio);
  if (input.translationAudio) form.append("translation_audio", input.translationAudio);
  if (input.image) form.append("image", input.image);

  const { data } = await api.post(`/dictionaries/${dictionaryId}/words`, form, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

export async function deleteWord(wordId: number): Promise<void> {
  await api.delete(`/words/${wordId}`);
}

export async function getWord(wordId: number): Promise<Word> {
  const { data } = await api.get(`/words/${wordId}`);
  return data;
}

/** Patch for the Word itself: text fields plus its own image/audio.
 * Only fields that are set are changed; the rest of the word (including
 * its translations) is left untouched. Pass a `remove*` flag to clear a
 * field/file instead of replacing it. */
export interface UpdateWordInput {
  word?: string;
  transcription?: string;
  removeTranscription?: boolean;
  categoryId?: number;
  removeCategory?: boolean;
  wordAudio?: File | null;
  removeWordAudio?: boolean;
  image?: File | null;
  removeImage?: boolean;
}

export async function updateWord(wordId: number, input: UpdateWordInput): Promise<Word> {
  const form = new FormData();
  if (input.word !== undefined) form.append("word", input.word);
  if (input.transcription !== undefined) form.append("transcription", input.transcription);
  if (input.removeTranscription) form.append("remove_transcription", "true");
  if (input.categoryId !== undefined) form.append("category_id", String(input.categoryId));
  if (input.removeCategory) form.append("remove_category", "true");
  if (input.wordAudio) form.append("word_audio", input.wordAudio);
  if (input.removeWordAudio) form.append("remove_word_audio", "true");
  if (input.image) form.append("image", input.image);
  if (input.removeImage) form.append("remove_image", "true");

  const { data } = await api.patch(`/words/${wordId}`, form, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

/** Appends one more grammatical form of the word in `language`. Always
 * creates a new row -- a word may have several forms in the same language,
 * unlike translations. */
export async function addWordForm(wordId: number, language: string, text: string): Promise<WordForm> {
  const form = new FormData();
  form.append("language", language);
  form.append("text", text);

  const { data } = await api.post(`/words/${wordId}/forms`, form, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

export async function deleteWordForm(wordId: number, formId: number): Promise<void> {
  await api.delete(`/words/${wordId}/forms/${formId}`);
}

/** Creates or updates the word's translation into `language`. */
export async function upsertTranslation(
  wordId: number,
  language: TranslationLanguage,
  input: { text: string; audio?: File | null; removeAudio?: boolean },
): Promise<WordTranslation> {
  const form = new FormData();
  form.append("text", input.text);
  if (input.audio) form.append("audio", input.audio);
  if (input.removeAudio) form.append("remove_audio", "true");

  const { data } = await api.put(`/words/${wordId}/translations/${language}`, form, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

export async function deleteTranslation(wordId: number, language: TranslationLanguage): Promise<void> {
  await api.delete(`/words/${wordId}/translations/${language}`);
}

/** Server-tracked state of one ZIP import -- either a dictionary (words)
 * ZIP or a phrases ZIP, both sharing this same shape (see the backend's
 * ImportJobOut). The browser never parses the ZIP or decides whether it's
 * valid -- it only starts the job and polls this by job_id, so a slow
 * import keeps running on the backend (and its result stays retrievable)
 * no matter what the admin's tab does in the meantime. `error_message` is
 * a specific reason (which word/phrase/category/path, or which JSON
 * problem), only set once `status === "failed"`; the count fields are only
 * set once `status === "completed"`, and only the pair matching what this
 * job actually imported (words + forms, or phrases) is non-null. */
export interface ImportJob {
  job_id: string;
  status: "pending" | "processing" | "completed" | "failed";
  error_message: string | null;
  categories_created: number | null;
  categories_reused: number | null;
  words_created: number | null;
  words_reused: number | null;
  forms_added: number | null;
  phrases_created: number | null;
  phrases_reused: number | null;
}

/** Dictionary import/export moves as a ZIP archive (dictionary.json --
 * fixed categories/words shape, each word optionally carrying `audio`/
 * `audio_tg` paths -- plus the audio files themselves under
 * audio/original/ and audio/tg/, see the backend's ImportPayload for the
 * authoritative shape). The admin only ever passes the archive through as
 * an opaque file/blob, never parses it client-side. Starting an import
 * only hands the file to the backend and gets a job_id back immediately;
 * use `getDictionaryImportJob` to poll for its actual result. */
export async function startDictionaryImport(dictionaryId: number, file: File): Promise<ImportJob> {
  const formData = new FormData();
  formData.append("file", file);
  const { data } = await api.post(`/dictionaries/${dictionaryId}/import`, formData);
  return data;
}

export async function getDictionaryImportJob(dictionaryId: number, jobId: string): Promise<ImportJob> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/import/${jobId}`);
  return data;
}

export async function exportDictionary(dictionaryId: number): Promise<Blob> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/export`, { responseType: "blob" });
  return data;
}

// --- Phrases -----------------------------------------------------------
// Separate entity from Word, own id (phrase_id) and own category
// namespace (PhraseCategory), same CRUD shape as Words/Categories.

export async function listPhraseCategories(dictionaryId: number): Promise<PhraseCategory[]> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/phrase-categories`);
  return data;
}

export async function createPhraseCategory(dictionaryId: number, name: string): Promise<PhraseCategory> {
  const { data } = await api.post(`/dictionaries/${dictionaryId}/phrase-categories`, { name });
  return data;
}

export async function listPhrases(dictionaryId: number, categoryId?: number): Promise<Phrase[]> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/phrases`, {
    params: categoryId !== undefined ? { category_id: categoryId } : undefined,
  });
  return data;
}

export interface CreatePhraseInput {
  original: string;
  translationTg: string;
  transcription?: string;
  categoryId?: number | null;
  originalAudio?: File | null;
  translationAudio?: File | null;
}

export async function createPhrase(dictionaryId: number, input: CreatePhraseInput): Promise<Phrase> {
  const form = new FormData();
  form.append("original", input.original);
  form.append("translation_tg", input.translationTg);
  if (input.transcription) form.append("transcription", input.transcription);
  if (input.categoryId != null) form.append("category_id", String(input.categoryId));
  if (input.originalAudio) form.append("original_audio", input.originalAudio);
  if (input.translationAudio) form.append("translation_audio", input.translationAudio);

  const { data } = await api.post(`/dictionaries/${dictionaryId}/phrases`, form, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

export async function getPhrase(phraseId: number): Promise<Phrase> {
  const { data } = await api.get(`/phrases/${phraseId}`);
  return data;
}

export interface UpdatePhraseInput {
  original?: string;
  transcription?: string;
  removeTranscription?: boolean;
  translationTg?: string;
  categoryId?: number;
  removeCategory?: boolean;
  originalAudio?: File | null;
  removeOriginalAudio?: boolean;
  translationAudio?: File | null;
  removeTranslationAudio?: boolean;
}

export async function updatePhrase(phraseId: number, input: UpdatePhraseInput): Promise<Phrase> {
  const form = new FormData();
  if (input.original !== undefined) form.append("original", input.original);
  if (input.transcription !== undefined) form.append("transcription", input.transcription);
  if (input.removeTranscription) form.append("remove_transcription", "true");
  if (input.translationTg !== undefined) form.append("translation_tg", input.translationTg);
  if (input.categoryId !== undefined) form.append("category_id", String(input.categoryId));
  if (input.removeCategory) form.append("remove_category", "true");
  if (input.originalAudio) form.append("original_audio", input.originalAudio);
  if (input.removeOriginalAudio) form.append("remove_original_audio", "true");
  if (input.translationAudio) form.append("translation_audio", input.translationAudio);
  if (input.removeTranslationAudio) form.append("remove_translation_audio", "true");

  const { data } = await api.patch(`/phrases/${phraseId}`, form, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

export async function deletePhrase(phraseId: number): Promise<void> {
  await api.delete(`/phrases/${phraseId}`);
}

/** Phrase import/export moves as a ZIP archive (phrases.json -- fixed
 * categories/phrases shape, each phrase optionally carrying `audio`/
 * `audio_tg` paths -- plus the audio files themselves under
 * audio/phrases/original/ and audio/phrases/tg/, see the backend's
 * ImportPhrasePayload for the authoritative shape), same principle as the
 * Word dictionary ZIP above. The admin only ever passes the archive through
 * as an opaque file/blob, never parses it client-side. Starting an import
 * only hands the file to the backend and gets a job_id back immediately;
 * use `getPhraseImportJob` to poll for its actual result. */
export async function startPhraseImport(dictionaryId: number, file: File): Promise<ImportJob> {
  const formData = new FormData();
  formData.append("file", file);
  const { data } = await api.post(`/dictionaries/${dictionaryId}/phrases/import`, formData);
  return data;
}

export async function getPhraseImportJob(dictionaryId: number, jobId: string): Promise<ImportJob> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/phrases/import/${jobId}`);
  return data;
}

export async function exportPhrases(dictionaryId: number): Promise<Blob> {
  const { data } = await api.get(`/dictionaries/${dictionaryId}/phrases/export`, { responseType: "blob" });
  return data;
}

// --- Exercise settings ---------------------------------------------------

export async function getExerciseSettings(exerciseKey: string): Promise<ExerciseSettings> {
  const { data } = await api.get(`/exercise-settings/${exerciseKey}`);
  return data;
}

export interface ExerciseSettingsInput {
  wordCount: number;
  // Only "Собери слово" uses these today; omit them for exercises that
  // only have a word count.
  wrongLetterCount?: number | null;
  minWordLength?: number | null;
  caseSensitive?: boolean | null;
  // How many points a right/wrong answer moves a word's score within a
  // lesson -- every exercise has these. Omit to fall back to that
  // exercise's own built-in default.
  correctPoints?: number | null;
  incorrectPoints?: number | null;
  // Whether this exercise can be picked for a new Lesson at all. Omit (or
  // null) to leave it enabled.
  enabled?: boolean | null;
  // Only "Услышь слово" uses this (how many word choices one round shows).
  optionCount?: number | null;
  // Only "Произнеси слово" uses this (0-100 minimum text-similarity to
  // accept a spoken answer as correct).
  speechMatchThreshold?: number | null;
}

export async function setExerciseSettings(
  exerciseKey: string,
  input: ExerciseSettingsInput,
): Promise<ExerciseSettings> {
  const { data } = await api.put(`/exercise-settings/${exerciseKey}`, {
    word_count: input.wordCount,
    wrong_letter_count: input.wrongLetterCount ?? null,
    min_word_length: input.minWordLength ?? null,
    case_sensitive: input.caseSensitive ?? null,
    correct_points: input.correctPoints ?? null,
    incorrect_points: input.incorrectPoints ?? null,
    enabled: input.enabled ?? null,
    option_count: input.optionCount ?? null,
    speech_match_threshold: input.speechMatchThreshold ?? null,
  });
  return data;
}

// --- Аналитика пользователей ---------------------------------------------
// Read-only: every number here is computed by the backend from existing
// Word/WordForm/WordProgress/Phrase data, using the exact same
// "is this phrase available" definition as the app's own "Мои фразы".

export async function listAnalyticsDictionaries(): Promise<AnalyticsDictionary[]> {
  const { data } = await api.get("/admin/analytics/dictionaries");
  return data;
}

export async function getUserPhraseAnalytics(
  userId: number,
  dictionaryId: number,
): Promise<UserPhraseAnalytics> {
  const { data } = await api.get(`/admin/analytics/users/${userId}`, {
    params: { dictionary_id: dictionaryId },
  });
  return data;
}

export async function listUserWordProgress(
  userId: number,
  dictionaryId: number,
): Promise<UserWordProgress[]> {
  const { data } = await api.get(`/admin/analytics/users/${userId}/words`, {
    params: { dictionary_id: dictionaryId },
  });
  return data;
}

export async function getWordDiagnostics(userId: number, wordId: number): Promise<WordDiagnostics> {
  const { data } = await api.get(`/admin/analytics/users/${userId}/words/${wordId}`);
  return data;
}

// --- Достижения ------------------------------------------------------------
// Achievement DEFINITIONS only -- individual users' earned status lives
// entirely on the backend and is never fetched/edited from here.

export async function listAchievements(): Promise<Achievement[]> {
  const { data } = await api.get("/admin/achievements");
  return data;
}

export async function listConditionTypes(): Promise<ConditionType[]> {
  const { data } = await api.get("/admin/achievements/condition-types");
  return data;
}

export interface AchievementInput {
  title: string;
  description: string;
  conditionType: string;
  conditionValue: number;
  color: string;
  visibility: AchievementVisibility;
  showBeforeUnlock: boolean;
  enabled: boolean;
  order: number;
  /** A real uploaded image -- never an emoji/text substitute. Omit on
   * update to leave the current icon untouched. */
  icon?: File | null;
  /** Update only: clears the icon instead of replacing it. */
  removeIcon?: boolean;
}

function achievementForm(input: AchievementInput): FormData {
  const form = new FormData();
  form.append("title", input.title);
  form.append("description", input.description);
  form.append("condition_type", input.conditionType);
  form.append("condition_value", String(input.conditionValue));
  form.append("color", input.color);
  form.append("visibility", input.visibility);
  form.append("show_before_unlock", String(input.showBeforeUnlock));
  form.append("enabled", String(input.enabled));
  form.append("order", String(input.order));
  if (input.icon) form.append("icon", input.icon);
  if (input.removeIcon) form.append("remove_icon", "true");
  return form;
}

export async function createAchievement(input: AchievementInput): Promise<Achievement> {
  const { data } = await api.post("/admin/achievements", achievementForm(input), {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

export async function updateAchievement(id: number, input: AchievementInput): Promise<Achievement> {
  const { data } = await api.patch(`/admin/achievements/${id}`, achievementForm(input), {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

// Throws with the backend's own 409 message when the achievement has
// already been earned by at least one user -- callers should show that
// message rather than a generic failure, since it's telling the admin
// exactly what to do instead (disable it).
export async function deleteAchievement(id: number): Promise<void> {
  await api.delete(`/admin/achievements/${id}`);
}

/** Persists the chain's full new order, front to back, from Admin Web's
 * drag-and-drop -- never only client-side/local state. */
export async function reorderAchievements(achievementIds: number[]): Promise<Achievement[]> {
  const { data } = await api.put("/admin/achievements/order", { achievement_ids: achievementIds });
  return data;
}

// --- Рейтинг -----------------------------------------------------------------
// Entirely separate backend system from Achievements above (app/rating/).

export async function getRatingSettings(): Promise<RatingSettings> {
  const { data } = await api.get("/admin/rating/settings");
  return data;
}

export async function updateRatingSettings(input: RatingSettings): Promise<RatingSettings> {
  const { data } = await api.put("/admin/rating/settings", input);
  return data;
}

export async function listRanks(): Promise<Rank[]> {
  const { data } = await api.get("/admin/rating/ranks");
  return data;
}

export interface RankInput {
  name: string;
  minPoints: number;
  maxPoints: number | null;
  color: string;
  enabled: boolean;
  /** A real uploaded image -- never emoji. Omit on update to leave the
   * current icon untouched. */
  icon?: File | null;
  /** Update only: clears the icon instead of replacing it. */
  removeIcon?: boolean;
}

function rankForm(input: RankInput): FormData {
  const form = new FormData();
  form.append("name", input.name);
  form.append("min_points", String(input.minPoints));
  if (input.maxPoints !== null) form.append("max_points", String(input.maxPoints));
  else form.append("clear_max_points", "true");
  form.append("color", input.color);
  form.append("enabled", String(input.enabled));
  if (input.icon) form.append("icon", input.icon);
  if (input.removeIcon) form.append("remove_icon", "true");
  return form;
}

export async function createRank(input: RankInput): Promise<Rank> {
  const { data } = await api.post("/admin/rating/ranks", rankForm(input), {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

export async function updateRank(id: number, input: RankInput): Promise<Rank> {
  const { data } = await api.patch(`/admin/rating/ranks/${id}`, rankForm(input), {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return data;
}

// Throws with the backend's own 409 message when a completed season's
// history already points to this rank -- callers should show that message
// (disable it instead of deleting).
export async function deleteRank(id: number): Promise<void> {
  await api.delete(`/admin/rating/ranks/${id}`);
}

export async function reorderRanks(rankIds: number[]): Promise<Rank[]> {
  const { data } = await api.put("/admin/rating/ranks/order", { rank_ids: rankIds });
  return data;
}

export async function listSeasons(): Promise<Season[]> {
  const { data } = await api.get("/admin/rating/seasons");
  return data;
}

export interface SeasonInput {
  name: string;
  /** ISO datetime. Omitted means "starts now". */
  startsAt?: string;
  /** ISO datetime. Omitted means "no scheduled end" -- only an admin ends it. */
  endsAt?: string;
}

// Several seasons may exist at once as long as their periods don't collide.
// A period starting exactly when another ends is NOT a collision: the
// backend hands over at that moment (409 with a readable reason otherwise).
export async function createSeason(input: SeasonInput): Promise<Season> {
  const { data } = await api.post("/admin/rating/seasons", {
    name: input.name,
    starts_at: input.startsAt,
    ends_at: input.endsAt,
  });
  return data;
}

export interface SeasonUpdateInput {
  name?: string;
  startsAt?: string;
  endsAt?: string;
  /** Turns a scheduled end back into "manual only" -- distinct from simply
   * not sending endsAt, which leaves it unchanged. */
  clearEndsAt?: boolean;
}

// Only a season that hasn't completed can be edited; a completed one is
// already frozen into every user's history.
export async function updateSeason(id: number, input: SeasonUpdateInput): Promise<Season> {
  const { data } = await api.patch(`/admin/rating/seasons/${id}`, {
    name: input.name,
    starts_at: input.startsAt,
    ends_at: input.endsAt,
    clear_ends_at: input.clearEndsAt,
  });
  return data;
}

// Only a SCHEDULED season can be deleted -- one that never ran, so it left
// no history behind.
export async function deleteSeason(id: number): Promise<void> {
  await api.delete(`/admin/rating/seasons/${id}`);
}

export async function setSeasonIcon(id: number, icon: File): Promise<Season> {
  const form = new FormData();
  form.append("icon", icon);
  const { data } = await api.put(`/admin/rating/seasons/${id}/icon`, form);
  return data;
}

export async function deleteSeasonIcon(id: number): Promise<Season> {
  const { data } = await api.delete(`/admin/rating/seasons/${id}/icon`);
  return data;
}

// Freezes every user's current points/rank into that season's history and
// applies the configured reset -- irreversible. The manual half of the two
// ways a season ends; the other is its own ends_at arriving.
export async function endSeason(id: number): Promise<Season> {
  const { data } = await api.post(`/admin/rating/seasons/${id}/end`);
  return data;
}

// --- Уровни слов ---------------------------------------------------------------

export async function listWordLevels(): Promise<WordLevel[]> {
  const { data } = await api.get("/admin/word-levels");
  return data;
}

export interface WordLevelInput {
  name: string;
  minPoints: number;
  maxPoints: number | null;
  enabled: boolean;
  order: number;
}

function wordLevelBody(input: WordLevelInput) {
  return {
    name: input.name,
    min_points: input.minPoints,
    ...(input.maxPoints === null ? { clear_max_points: true } : { max_points: input.maxPoints }),
    enabled: input.enabled,
    order: input.order,
  };
}

export async function createWordLevel(input: WordLevelInput): Promise<WordLevel> {
  const { data } = await api.post("/admin/word-levels", {
    name: input.name,
    min_points: input.minPoints,
    ...(input.maxPoints !== null ? { max_points: input.maxPoints } : {}),
    enabled: input.enabled,
    order: input.order,
  });
  return data;
}

export async function updateWordLevel(id: number, input: WordLevelInput): Promise<WordLevel> {
  const { data } = await api.patch(`/admin/word-levels/${id}`, wordLevelBody(input));
  return data;
}

// Throws with the backend's own 409 message when a Quest still targets
// this level -- disable it instead.
export async function deleteWordLevel(id: number): Promise<void> {
  await api.delete(`/admin/word-levels/${id}`);
}

export async function reorderWordLevels(ids: number[]): Promise<WordLevel[]> {
  const { data } = await api.put("/admin/word-levels/order", { word_level_ids: ids });
  return data;
}

// --- Квесты ----------------------------------------------------------------------

export async function listQuests(): Promise<Quest[]> {
  const { data } = await api.get("/admin/quests");
  return data;
}

export async function listQuestExerciseTypes(): Promise<string[]> {
  const { data } = await api.get("/admin/quests/exercise-types");
  return data;
}

export interface QuestInput {
  name: string;
  wordLevelId: number;
  exerciseKey: string;
  rewardPoints: number;
  /** Successful attempts per day that count as "done". Minimum 1. */
  dailyTarget: number;
  enabled: boolean;
  order: number;
}

function questBody(input: QuestInput) {
  return {
    name: input.name,
    word_level_id: input.wordLevelId,
    exercise_key: input.exerciseKey,
    reward_points: input.rewardPoints,
    daily_target: input.dailyTarget,
    enabled: input.enabled,
    order: input.order,
  };
}

export async function createQuest(input: QuestInput): Promise<Quest> {
  const { data } = await api.post("/admin/quests", questBody(input));
  return data;
}

export async function updateQuest(id: number, input: QuestInput): Promise<Quest> {
  const { data } = await api.patch(`/admin/quests/${id}`, questBody(input));
  return data;
}

// Throws with the backend's own 409 message when the quest has already
// been completed by at least one user -- disable it instead.
export async function deleteQuest(id: number): Promise<void> {
  await api.delete(`/admin/quests/${id}`);
}

export async function reorderQuests(ids: number[]): Promise<Quest[]> {
  const { data } = await api.put("/admin/quests/order", { quest_ids: ids });
  return data;
}

// --- Слоганы -------------------------------------------------------------------

export async function listSlogans(): Promise<Slogan[]> {
  const { data } = await api.get("/admin/slogans");
  return data;
}

export interface SloganInput {
  text: string;
  enabled: boolean;
  order?: number;
}

export async function createSlogan(input: SloganInput): Promise<Slogan> {
  const { data } = await api.post("/admin/slogans", input);
  return data;
}

// Only the fields passed are changed, so toggling a slogan off never
// rewrites its text.
export async function updateSlogan(id: number, input: Partial<SloganInput>): Promise<Slogan> {
  const { data } = await api.patch(`/admin/slogans/${id}`, input);
  return data;
}

export async function reorderSlogans(sloganIds: number[]): Promise<Slogan[]> {
  const { data } = await api.put("/admin/slogans/order", { slogan_ids: sloganIds });
  return data;
}

export async function deleteSlogan(id: number): Promise<void> {
  await api.delete(`/admin/slogans/${id}`);
}

// --- Уведомления ---------------------------------------------------------------

// Sends one message to one user. Goes through the same backend service any
// future automatic rule will use -- this is a caller of it, not a second way
// to create notifications.
export async function sendNotification(input: {
  userId: number;
  title?: string;
  body: string;
}): Promise<AdminNotification> {
  const { data } = await api.post("/admin/notifications", {
    user_id: input.userId,
    title: input.title || null,
    body: input.body,
  });
  return data;
}

// Everything sent, newest first -- or one user's thread. Will include
// automatically sent messages once rules exist, since they are the same rows.
export async function listSentNotifications(userId?: number): Promise<AdminNotification[]> {
  const { data } = await api.get("/admin/notifications", {
    params: userId !== undefined ? { user_id: userId } : undefined,
  });
  return data;
}
