"""add dictionary alphabet and build_word exercise settings

Revision ID: 11598a9e9e46
Revises: c756e5a18581
Create Date: 2026-09-17 16:24:21.577544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11598a9e9e46'
down_revision: Union[str, None] = 'c756e5a18581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionaries', sa.Column('alphabet', sa.String(length=256), nullable=True))
    op.add_column('exercise_settings', sa.Column('wrong_letter_count', sa.Integer(), nullable=True))
    op.add_column('exercise_settings', sa.Column('min_word_length', sa.Integer(), nullable=True))
    op.add_column('exercise_settings', sa.Column('case_sensitive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_settings', 'case_sensitive')
    op.drop_column('exercise_settings', 'min_word_length')
    op.drop_column('exercise_settings', 'wrong_letter_count')
    op.drop_column('dictionaries', 'alphabet')
    # ### end Alembic commands ###
