"""add lessons, word progress and learning settings

Revision ID: 167a2ac6c8a6
Revises: df40bef3b199
Create Date: 2026-09-19 22:43:38.521407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167a2ac6c8a6'
down_revision: Union[str, None] = 'df40bef3b199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold_score', sa.Integer(), server_default='60', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_dictionary_id'), 'lessons', ['dictionary_id'], unique=False)
    op.create_index(op.f('ix_lessons_user_id'), 'lessons', ['user_id'], unique=False)
    op.create_index('uq_active_lesson_per_user_dictionary', 'lessons', ['user_id', 'dictionary_id'], unique=True, postgresql_where=sa.text('is_completed = false'))
    op.create_table('lesson_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('exercise_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'exercise_key', name='uq_lesson_exercise_lesson_key')
    )
    op.create_index(op.f('ix_lesson_exercises_lesson_id'), 'lesson_exercises', ['lesson_id'], unique=False)
    op.create_table('lesson_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'word_id', name='uq_lesson_word_lesson_word')
    )
    op.create_index(op.f('ix_lesson_words_lesson_id'), 'lesson_words', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_words_word_id'), 'lesson_words', ['word_id'], unique=False)
    op.create_table('word_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_word_progress_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_word_progress_user_word')
    )
    op.create_index(op.f('ix_word_progress_user_id'), 'word_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_word_progress_word_id'), 'word_progress', ['word_id'], unique=False)
    op.add_column('exercise_settings', sa.Column('correct_points', sa.Integer(), nullable=True))
    op.add_column('exercise_settings', sa.Column('incorrect_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # --- Data migration: the old binary LearnedWord flag becomes the new
    # WordProgress system's starting point -- a word a user had already
    # marked "Изучил" under the old flashcard flow is carried over as
    # already fully learned (score=100), so nobody's existing progress is
    # silently lost when the old system is removed. Never touches Word
    # itself, and ON CONFLICT is a no-op safety net in case this migration
    # is ever re-run against a database that already has WordProgress rows.
    op.execute(
        """
        INSERT INTO word_progress (user_id, word_id, score, updated_at)
        SELECT user_id, word_id, 100, learned_at FROM learned_words
        ON CONFLICT (user_id, word_id) DO NOTHING
        """
    )
    op.execute("INSERT INTO learning_settings (id, threshold_score) VALUES (1, 60)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_settings', 'incorrect_points')
    op.drop_column('exercise_settings', 'correct_points')
    op.drop_index(op.f('ix_word_progress_word_id'), table_name='word_progress')
    op.drop_index(op.f('ix_word_progress_user_id'), table_name='word_progress')
    op.drop_table('word_progress')
    op.drop_index(op.f('ix_lesson_words_word_id'), table_name='lesson_words')
    op.drop_index(op.f('ix_lesson_words_lesson_id'), table_name='lesson_words')
    op.drop_table('lesson_words')
    op.drop_index(op.f('ix_lesson_exercises_lesson_id'), table_name='lesson_exercises')
    op.drop_table('lesson_exercises')
    op.drop_index('uq_active_lesson_per_user_dictionary', table_name='lessons', postgresql_where=sa.text('is_completed = false'))
    op.drop_index(op.f('ix_lessons_user_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_dictionary_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('learning_settings')
    # ### end Alembic commands ###
