"""add categories and word_forms, drop quizlet

Revision ID: 30813673fe7c
Revises: 1cc08e8fcbad
Create Date: 2026-09-16 03:45:41.727035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30813673fe7c'
down_revision: Union[str, None] = '1cc08e8fcbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dictionary_id', 'name', name='uq_category_dictionary_name')
    )
    op.create_index(op.f('ix_categories_dictionary_id'), 'categories', ['dictionary_id'], unique=False)
    op.create_table('word_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_forms_word_id'), 'word_forms', ['word_id'], unique=False)
    op.add_column('words', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_words_category_id'), 'words', ['category_id'], unique=False)
    op.create_foreign_key(None, 'words', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('words', 'quizlet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('quizlet', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_index(op.f('ix_words_category_id'), table_name='words')
    op.drop_column('words', 'category_id')
    op.drop_index(op.f('ix_word_forms_word_id'), table_name='word_forms')
    op.drop_table('word_forms')
    op.drop_index(op.f('ix_categories_dictionary_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
