"""add priority system

Revision ID: 3c0cdf54b6a2
Revises: 5510f037d1f7
Create Date: 2026-09-25 19:27:11.983622

Every number this migration inserts is a STARTING EXAMPLE, editable
through Admin Web from the moment this lands -- none of it is business
math anyone has signed off on (see app/priority/'s own module docstring).
The word_level_weights UPDATE below is a best-effort match against the
specific ranges this project's own WordLevel ladder happens to use today
(0-35/40-45/50-55/60-65/70-75/80-100); an environment whose ladder looks
different simply leaves every level at its column default (0) until an
admin sets real weights -- never an error, never a guess at a ladder that
isn't there.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0cdf54b6a2'
down_revision: Union[str, None] = '5510f037d1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_level_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_score IS NULL OR max_score >= min_score', name='ck_priority_level_range_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_recency_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('contribution', sa.Float(), server_default='0', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_days IS NULL OR max_days >= min_days', name='ck_priority_recency_range_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_level', sa.Float(), server_default='1', nullable=False),
    sa.Column('weight_recent_errors', sa.Float(), server_default='1', nullable=False),
    sa.Column('weight_recency', sa.Float(), server_default='1', nullable=False),
    sa.Column('weight_stability', sa.Float(), server_default='1', nullable=False),
    sa.Column('window5_weight', sa.Float(), server_default='1', nullable=False),
    sa.Column('window10_weight', sa.Float(), server_default='0.6', nullable=False),
    sa.Column('window20_weight', sa.Float(), server_default='0.3', nullable=False),
    sa.Column('stability_window', sa.Integer(), server_default='10', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_stability_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_percent', sa.Integer(), nullable=False),
    sa.Column('max_percent', sa.Integer(), nullable=False),
    sa.Column('contribution', sa.Float(), server_default='0', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_percent >= min_percent', name='ck_priority_stability_range_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lessons', sa.Column('is_adaptive', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('word_levels', sa.Column('priority_weight', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # --- Starting example data -- see this migration's own docstring ---

    op.execute("INSERT INTO priority_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING")

    # Word level -> priority contribution: best-effort, matched by this
    # project's own current ranges (see docstring). A "новое" word pulls
    # priority up the most, "закреплено" not at all.
    level_weights = [
        (0, 35, 100),
        (40, 45, 80),
        (50, 55, 60),
        (60, 65, 40),
        (70, 75, 20),
        (80, 100, 0),
    ]
    for min_points, max_points, weight in level_weights:
        op.execute(
            sa.text(
                "UPDATE word_levels SET priority_weight = :weight "
                "WHERE min_points = :min_points AND max_points = :max_points"
            ).bindparams(weight=weight, min_points=min_points, max_points=max_points)
        )

    op.execute(
        """
        INSERT INTO priority_recency_bands (name, min_days, max_days, contribution, "order") VALUES
            ('Сегодня', 0, 0, 0, 0),
            ('1-2 дня', 1, 2, 20, 1),
            ('3-5 дней', 3, 5, 45, 2),
            ('6-10 дней', 6, 10, 70, 3),
            ('11+ дней', 11, NULL, 100, 4)
        """
    )

    op.execute(
        """
        INSERT INTO priority_stability_bands (name, min_percent, max_percent, contribution, "order") VALUES
            ('Очень низкая', 0, 39, 100, 0),
            ('Низкая', 40, 59, 70, 1),
            ('Средняя', 60, 74, 45, 2),
            ('Высокая', 75, 89, 20, 3),
            ('Очень высокая', 90, 100, 0, 4)
        """
    )

    op.execute(
        """
        INSERT INTO priority_level_bands (name, min_score, max_score, "order") VALUES
            ('Минимальный', 0, 19, 0),
            ('Низкий', 20, 39, 1),
            ('Средний', 40, 59, 2),
            ('Высокий', 60, 79, 3),
            ('Критический', 80, NULL, 4)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_levels', 'priority_weight')
    op.drop_column('lessons', 'is_adaptive')
    op.drop_table('priority_stability_bands')
    op.drop_table('priority_settings')
    op.drop_table('priority_recency_bands')
    op.drop_table('priority_level_bands')
    # ### end Alembic commands ###
