"""add exercise engine settings columns

Revision ID: 501bd4123145
Revises: 7d42ac3bf8e4
Create Date: 2026-09-20 23:43:09.142211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501bd4123145'
down_revision: Union[str, None] = '7d42ac3bf8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_settings', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('exercise_settings', sa.Column('option_count', sa.Integer(), nullable=True))
    op.add_column('exercise_settings', sa.Column('speech_match_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_settings', 'speech_match_threshold')
    op.drop_column('exercise_settings', 'option_count')
    op.drop_column('exercise_settings', 'enabled')
    # ### end Alembic commands ###
