"""add word attempts history

Revision ID: 5510f037d1f7
Revises: a91f4c72e5d8
Create Date: 2026-09-25 17:44:00.174494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5510f037d1f7'
down_revision: Union[str, None] = 'a91f4c72e5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('exercise_key', sa.String(length=64), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_attempts_created_at'), 'word_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_word_attempts_user_id'), 'word_attempts', ['user_id'], unique=False)
    op.create_index('ix_word_attempts_user_word', 'word_attempts', ['user_id', 'word_id'], unique=False)
    op.create_index(op.f('ix_word_attempts_word_id'), 'word_attempts', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_attempts_word_id'), table_name='word_attempts')
    op.drop_index('ix_word_attempts_user_word', table_name='word_attempts')
    op.drop_index(op.f('ix_word_attempts_user_id'), table_name='word_attempts')
    op.drop_index(op.f('ix_word_attempts_created_at'), table_name='word_attempts')
    op.drop_table('word_attempts')
    # ### end Alembic commands ###
