"""add phrases_created and phrases_reused to import_jobs

Revision ID: 7d42ac3bf8e4
Revises: 167a2ac6c8a6
Create Date: 2026-09-20 03:41:18.805963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d42ac3bf8e4'
down_revision: Union[str, None] = '167a2ac6c8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('phrases_created', sa.Integer(), nullable=True))
    op.add_column('import_jobs', sa.Column('phrases_reused', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'phrases_reused')
    op.drop_column('import_jobs', 'phrases_created')
    # ### end Alembic commands ###
