"""achievements v2: uploaded icons, color, visibility, activity streak

Revision ID: 8ebb29880ef3
Revises: 6320f4d687ab
Create Date: 2026-09-21 20:10:36.229711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebb29880ef3'
down_revision: Union[str, None] = '6320f4d687ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_activity_day')
    )
    op.create_index(op.f('ix_user_activity_days_user_id'), 'user_activity_days', ['user_id'], unique=False)
    op.add_column('achievements', sa.Column('icon_key', sa.String(length=500), nullable=True))
    op.add_column('achievements', sa.Column('color', sa.String(length=9), server_default='#6366F1', nullable=False))
    op.add_column('achievements', sa.Column('visibility', sa.String(length=16), server_default='visible', nullable=False))
    op.add_column('achievements', sa.Column('show_before_unlock', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('achievements', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('icon', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('achievements', 'show_before_unlock')
    op.drop_column('achievements', 'visibility')
    op.drop_column('achievements', 'color')
    op.drop_column('achievements', 'icon_key')
    op.drop_index(op.f('ix_user_activity_days_user_id'), table_name='user_activity_days')
    op.drop_table('user_activity_days')
    # ### end Alembic commands ###
