"""add seasonal rating system

Revision ID: 953befd7ab1b
Revises: 8ebb29880ef3
Create Date: 2026-09-21 23:41:38.970872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953befd7ab1b'
down_revision: Union[str, None] = '8ebb29880ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('icon_key', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=9), server_default='#6366F1', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_points IS NULL OR max_points >= min_points', name='ck_rank_range_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points_per_learned_word', sa.Integer(), server_default='10', nullable=False),
    sa.Column('season_reset_mode', sa.String(length=16), server_default='fixed', nullable=False),
    sa.Column('season_reset_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', name='uq_season_history_once')
    )
    op.create_index(op.f('ix_season_history_season_id'), 'season_history', ['season_id'], unique=False)
    op.create_index(op.f('ix_season_history_user_id'), 'season_history', ['user_id'], unique=False)
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ratings_user_id'), 'user_ratings', ['user_id'], unique=True)
    op.create_table('user_word_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word_points_once')
    )
    op.create_index(op.f('ix_user_word_points_user_id'), 'user_word_points', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_word_points_word_id'), 'user_word_points', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_word_points_word_id'), table_name='user_word_points')
    op.drop_index(op.f('ix_user_word_points_user_id'), table_name='user_word_points')
    op.drop_table('user_word_points')
    op.drop_index(op.f('ix_user_ratings_user_id'), table_name='user_ratings')
    op.drop_table('user_ratings')
    op.drop_index(op.f('ix_season_history_user_id'), table_name='season_history')
    op.drop_index(op.f('ix_season_history_season_id'), table_name='season_history')
    op.drop_table('season_history')
    op.drop_table('seasons')
    op.drop_table('rating_settings')
    op.drop_table('ranks')
    # ### end Alembic commands ###
