"""add learning sessions and learned words

Revision ID: 978cdf60250a
Revises: ae82dc521ea7
Create Date: 2026-09-16 09:39:26.788835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978cdf60250a'
down_revision: Union[str, None] = 'ae82dc521ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_dictionary_id'), 'learning_sessions', ['dictionary_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_index('uq_active_learning_session_per_user_dictionary', 'learning_sessions', ['user_id', 'dictionary_id'], unique=True, postgresql_where=sa.text('is_completed = false'))
    op.create_table('learned_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_learned_word_user_word')
    )
    op.create_index(op.f('ix_learned_words_user_id'), 'learned_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_learned_words_word_id'), 'learned_words', ['word_id'], unique=False)
    op.create_table('learning_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'word_id', name='uq_session_item_session_word')
    )
    op.create_index(op.f('ix_learning_session_items_session_id'), 'learning_session_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_learning_session_items_word_id'), 'learning_session_items', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_session_items_word_id'), table_name='learning_session_items')
    op.drop_index(op.f('ix_learning_session_items_session_id'), table_name='learning_session_items')
    op.drop_table('learning_session_items')
    op.drop_index(op.f('ix_learned_words_word_id'), table_name='learned_words')
    op.drop_index(op.f('ix_learned_words_user_id'), table_name='learned_words')
    op.drop_table('learned_words')
    op.drop_index('uq_active_learning_session_per_user_dictionary', table_name='learning_sessions', postgresql_where=sa.text('is_completed = false'))
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_dictionary_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
