"""add phrases and phrase categories

Revision ID: ae82dc521ea7
Revises: 30813673fe7c
Create Date: 2026-09-16 08:50:00.343909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae82dc521ea7'
down_revision: Union[str, None] = '30813673fe7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dictionary_id', 'name', name='uq_phrase_category_dictionary_name')
    )
    op.create_index(op.f('ix_phrase_categories_dictionary_id'), 'phrase_categories', ['dictionary_id'], unique=False)
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('original', sa.String(length=1000), nullable=False),
    sa.Column('transcription', sa.String(length=255), nullable=True),
    sa.Column('translation_tg', sa.String(length=1000), nullable=False),
    sa.Column('original_audio_key', sa.Text(), nullable=True),
    sa.Column('translation_audio_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['phrase_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrases_category_id'), 'phrases', ['category_id'], unique=False)
    op.create_index(op.f('ix_phrases_dictionary_id'), 'phrases', ['dictionary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrases_dictionary_id'), table_name='phrases')
    op.drop_index(op.f('ix_phrases_category_id'), table_name='phrases')
    op.drop_table('phrases')
    op.drop_index(op.f('ix_phrase_categories_dictionary_id'), table_name='phrase_categories')
    op.drop_table('phrase_categories')
    # ### end Alembic commands ###
