"""add exercise settings

Revision ID: c756e5a18581
Revises: 978cdf60250a
Create Date: 2026-09-17 12:55:14.511584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c756e5a18581'
down_revision: Union[str, None] = '978cdf60250a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_key', sa.String(length=64), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_settings_exercise_key'), 'exercise_settings', ['exercise_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_settings_exercise_key'), table_name='exercise_settings')
    op.drop_table('exercise_settings')
    # ### end Alembic commands ###
