"""add import_jobs table

Revision ID: df40bef3b199
Revises: 11598a9e9e46
Create Date: 2026-09-19 14:30:47.618400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df40bef3b199'
down_revision: Union[str, None] = '11598a9e9e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('categories_created', sa.Integer(), nullable=True),
    sa.Column('categories_reused', sa.Integer(), nullable=True),
    sa.Column('words_created', sa.Integer(), nullable=True),
    sa.Column('words_reused', sa.Integer(), nullable=True),
    sa.Column('forms_added', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_dictionary_id'), 'import_jobs', ['dictionary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_dictionary_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
