"""add word reinforcement levels and quests

Revision ID: f45697cd04e3
Revises: 953befd7ab1b
Create Date: 2026-09-22 01:33:12.607401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45697cd04e3'
down_revision: Union[str, None] = '953befd7ab1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_points IS NULL OR max_points >= min_points', name='ck_word_level_range_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('word_level_id', sa.Integer(), nullable=False),
    sa.Column('exercise_key', sa.String(length=64), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['word_level_id'], ['word_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quest_word_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('used_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', 'used_date', name='uq_user_quest_word_day')
    )
    op.create_index(op.f('ix_user_quest_word_days_user_id'), 'user_quest_word_days', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_quest_word_days_word_id'), 'user_quest_word_days', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quest_word_days_word_id'), table_name='user_quest_word_days')
    op.drop_index(op.f('ix_user_quest_word_days_user_id'), table_name='user_quest_word_days')
    op.drop_table('user_quest_word_days')
    op.drop_table('quests')
    op.drop_table('word_levels')
    # ### end Alembic commands ###
